# Generated by Django 4.1.3 on 2022-12-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0003_direcciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=60)),
                ('antiguedad', models.IntegerField()),
            ],
        ),
    ]
